export const users = [
  {
    id: "1",
    name: "Sarah Jenkins",
    title: "Senior Frontend Engineer at TechCorp",
    company: "TechCorp",
    location: "San Francisco, CA",
    about: "Passionate about creating beautiful, accessible, and high-performance web applications using React and Next.js.",
    avatar: "https://i.pravatar.cc/150?u=sarah",
    connections: 500,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Product Designer at Designify",
    company: "Designify",
    location: "New York, NY",
    about: "Focusing on user-centric design and building scalable design systems.",
    avatar: "https://i.pravatar.cc/150?u=michael",
    connections: 342,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    title: "Full Stack Developer",
    company: "Freelance",
    location: "Austin, TX",
    about: "Building full-stack applications with Node.js, Express, and React. Open source contributor.",
    avatar: "https://i.pravatar.cc/150?u=emily",
    connections: 128,
  },
  {
    id: "4",
    name: "David Kim",
    title: "Engineering Manager at StartupX",
    company: "StartupX",
    location: "Seattle, WA",
    about: "Leading high-performing engineering teams and scaling infrastructure.",
    avatar: "https://i.pravatar.cc/150?u=david",
    connections: 890,
  },
  {
    id: "5",
    name: "Jessica Taylor",
    title: "DevOps Engineer",
    company: "CloudNet",
    location: "Denver, CO",
    about: "Automating all the things. Kubernetes enthusiast and CI/CD expert.",
    avatar: "https://i.pravatar.cc/150?u=jessica",
    connections: 412,
  },
  {
    id: "6",
    name: "Alex Johnson",
    title: "Data Scientist at AI Solutions",
    company: "AI Solutions",
    location: "Boston, MA",
    about: "Working on NLP and machine learning models for healthcare applications.",
    avatar: "https://i.pravatar.cc/150?u=alex",
    connections: 275,
  }
];
