import { Job } from './types';

// ─── REMOTE JOBS ─────────────────────────────────────────────────────────────
export const remoteJobs: Job[] = [
  {
    id: 1,
    title: 'Senior Full-Stack Engineer',
    company: 'Linear',
    logo: 'https://logo.clearbit.com/linear.app',
    workStyle: 'Remote only',
    location: 'Everywhere',
    salary: '$160k – $200k',
    equity: '0.05% – 0.2%',
    posted: 'today',
    category: 'Engineering',
    type: 'remote',
    experience: 'Senior',
    description: 'Linear is building the future of project management. We are looking for a senior full-stack engineer to help us scale our product to millions of users. You will work on core product features, infrastructure improvements, and developer tooling.',
    requirements: ['5+ years full-stack experience', 'TypeScript/React expertise', 'Node.js backend experience', 'PostgreSQL proficiency', 'Experience with distributed systems'],
    responsibilities: ['Build and ship features end-to-end', 'Improve platform performance and reliability', 'Collaborate with design and product', 'Participate in on-call rotation', 'Mentor junior engineers'],
    benefits: ['Fully remote', '$5k home office budget', 'Unlimited PTO', 'Top-tier health insurance', 'Annual team retreats'],
    skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'GraphQL', 'AWS'],
    aboutCompany: 'Linear is a project management tool built for modern software teams. We believe software should be fast, opinionated, and beautiful. Our team is small, focused, and ships fast.',
  },
  {
    id: 2,
    title: 'Staff Software Engineer',
    company: 'Vercel',
    logo: 'https://logo.clearbit.com/vercel.com',
    workStyle: 'Remote only',
    location: 'Everywhere',
    salary: '$180k – $240k',
    equity: '0.1% – 0.3%',
    posted: 'today',
    category: 'Engineering',
    type: 'remote',
    experience: 'Staff',
    description: 'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. We are looking for a Staff Software Engineer to join our Runtime team.',
    requirements: ['8+ years software engineering', 'Deep knowledge of distributed systems', 'Experience with serverless architecture', 'Strong TypeScript/Rust skills'],
    responsibilities: ['Lead technical direction for runtime team', 'Design and implement critical infrastructure', 'Drive architectural decisions', 'Mentor engineers across teams'],
    benefits: ['100% remote', 'Equity package', 'Health, dental, vision', 'Learning budget $2k/yr', 'Home office stipend'],
    skills: ['TypeScript', 'Rust', 'Go', 'Edge Computing', 'AWS', 'Kubernetes'],
    aboutCompany: 'Vercel is the platform for frontend developers. We enable teams to build, deploy, and scale products faster than ever — without the operational overhead.',
  },
  {
    id: 3,
    title: 'Remote DevOps Engineer',
    company: 'Fly.io',
    logo: 'https://logo.clearbit.com/fly.io',
    workStyle: 'Remote only',
    location: 'Everywhere',
    salary: '$140k – $180k',
    posted: 'today',
    category: 'Engineering',
    type: 'remote',
    experience: 'Mid',
    description: 'Fly.io is a platform for running full stack apps and databases close to users. We need a DevOps engineer who loves infrastructure automation and helping developers ship faster.',
    requirements: ['3+ years DevOps/SRE', 'Kubernetes expertise', 'Terraform/Pulumi', 'Strong Linux background', 'Incident response experience'],
    responsibilities: ['Manage multi-region infrastructure', 'Build deployment pipelines', 'Improve observability and alerting', 'Reduce toil through automation'],
    benefits: ['Fully async remote', 'Health insurance', '401k match', 'Home office budget', 'Conference allowance'],
    skills: ['Kubernetes', 'Terraform', 'Go', 'Prometheus', 'Linux', 'PostgreSQL'],
    aboutCompany: 'Fly.io runs your apps close to users with our global anycast network. Deploy containers near users in 30+ regions around the world.',
  },
  {
    id: 4,
    title: 'Backend Engineer - Payments',
    company: 'Stripe',
    logo: 'https://logo.clearbit.com/stripe.com',
    workStyle: 'Remote',
    location: 'US / EU',
    salary: '$170k – $220k',
    equity: '0.02% – 0.08%',
    posted: 'yesterday',
    category: 'Engineering',
    type: 'remote',
    experience: 'Senior',
    description: 'Stripe builds financial infrastructure for the internet. Our Payments team is responsible for processing billions of dollars in transactions. We are looking for a backend engineer passionate about reliability and scale.',
    requirements: ['5+ years backend engineering', 'Experience with high-throughput systems', 'Strong Java or Ruby experience', 'Understanding of financial systems'],
    responsibilities: ['Build and maintain payments APIs', 'Ensure 99.999% uptime', 'Improve fraud detection systems', 'Collaborate with compliance team'],
    benefits: ['Remote-first', 'Exceptional health benefits', 'RSUs', '401k with match', 'Generous parental leave'],
    skills: ['Java', 'Ruby', 'MySQL', 'Redis', 'Kafka', 'gRPC'],
    aboutCompany: 'Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world\'s largest enterprises to the most ambitious startups—use Stripe to accept payments.',
  },
  {
    id: 5,
    title: 'Remote Product Engineer',
    company: 'Notion',
    logo: 'https://logo.clearbit.com/notion.so',
    workStyle: 'Remote',
    location: 'Americas',
    salary: '$150k – $195k',
    equity: '0.01% – 0.05%',
    posted: 'yesterday',
    category: 'Product',
    type: 'remote',
    experience: 'Mid',
    description: 'Notion is on a mission to make toolmaking ubiquitous. We are looking for a product engineer who is passionate about building beautiful, powerful software used by millions.',
    requirements: ['3+ years product engineering', 'React and TypeScript', 'Strong product intuition', 'Experience with collaborative editors a plus'],
    responsibilities: ['Build core editor features', 'Improve performance of real-time collaboration', 'Work closely with design', 'Drive product quality'],
    benefits: ['Remote flexible', 'Health coverage', 'Notion credit', 'Learning stipend', 'Team offsites'],
    skills: ['React', 'TypeScript', 'Node.js', 'SQLite', 'CRDTs', 'WebSockets'],
    aboutCompany: 'Notion is a connected workspace where better, faster work happens. We help teams move faster, stay aligned, and get more done.',
  },
];

// ─── TECH JOBS ───────────────────────────────────────────────────────────────
export const techJobs: Job[] = [
  {
    id: 101,
    title: 'Senior ML Engineer',
    company: 'OpenAI',
    logo: 'https://logo.clearbit.com/openai.com',
    workStyle: 'Onsite or remote',
    location: 'San Francisco',
    salary: '$250k – $370k',
    equity: '0.05% – 0.5%',
    posted: 'today',
    category: 'AI/ML',
    type: 'full-time',
    experience: 'Senior',
    description: 'OpenAI\'s mission is to ensure that artificial general intelligence benefits all of humanity. We are looking for a Senior ML Engineer to work on training and deploying large language models at scale.',
    requirements: ['5+ years ML engineering', 'Deep learning frameworks (PyTorch)', 'Experience training large models', 'Strong Python skills', 'GPU cluster experience'],
    responsibilities: ['Train and fine-tune large language models', 'Optimize training infrastructure', 'Collaborate with research team', 'Build ML tooling and pipelines'],
    benefits: ['Competitive salary + equity', 'Top health benefits', 'Daily catered meals', 'Gym membership', 'Unlimited PTO'],
    skills: ['Python', 'PyTorch', 'CUDA', 'Distributed Training', 'Kubernetes', 'MLflow'],
    aboutCompany: 'OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity.',
  },
  {
    id: 102,
    title: 'iOS Engineer',
    company: 'Apple',
    logo: 'https://logo.clearbit.com/apple.com',
    workStyle: 'In office',
    location: 'Cupertino, CA',
    salary: '$190k – $270k',
    posted: 'today',
    category: 'Mobile',
    type: 'full-time',
    experience: 'Senior',
    description: 'Join Apple\'s iOS platform team to build the operating system used by over 1 billion people. You will work on core framework improvements and new platform features.',
    requirements: ['Swift/Objective-C mastery', '5+ years iOS development', 'Deep UIKit/SwiftUI knowledge', 'Performance optimization experience'],
    responsibilities: ['Build core iOS features', 'Optimize system performance', 'Work with hardware teams', 'Review and mentor engineers'],
    benefits: ['ESPP', 'Health/dental/vision', '401k with match', 'On-site amenities', 'Product discounts'],
    skills: ['Swift', 'SwiftUI', 'UIKit', 'Objective-C', 'XCTest', 'Instruments'],
    aboutCompany: 'Apple designs and builds its own operating systems, hardware, application software, and services. We are dedicated to making the best products in the world.',
  },
  {
    id: 103,
    title: 'Platform Engineer',
    company: 'GitHub',
    logo: 'https://logo.clearbit.com/github.com',
    workStyle: 'Remote',
    location: 'Everywhere',
    salary: '$155k – $195k',
    equity: '0.02% – 0.06%',
    posted: 'today',
    category: 'Engineering',
    type: 'remote',
    experience: 'Mid',
    description: 'GitHub is where the world builds software. Join the Platform team to build the infrastructure that 100M+ developers rely on every day.',
    requirements: ['4+ years platform/infra engineering', 'Ruby on Rails', 'MySQL at scale', 'Experience with large-scale web systems'],
    responsibilities: ['Scale core platform services', 'Improve developer experience', 'Lead technical initiatives', 'On-call support rotation'],
    benefits: ['Remote-first', 'RSUs', 'Health benefits', '$2k home office', 'Professional development'],
    skills: ['Ruby', 'Rails', 'MySQL', 'Redis', 'GitHub Actions', 'Terraform'],
    aboutCompany: 'GitHub is the complete developer platform to build, scale, and deliver secure software. We are the world\'s largest developer community.',
  },
  {
    id: 104,
    title: 'Security Engineer',
    company: 'Cloudflare',
    logo: 'https://logo.clearbit.com/cloudflare.com',
    workStyle: 'Remote only',
    location: 'US',
    salary: '$160k – $200k',
    equity: '0.01% – 0.05%',
    posted: 'yesterday',
    category: 'Security',
    type: 'remote',
    experience: 'Senior',
    description: 'Cloudflare secures and accelerates any Internet application online without adding hardware, installing software, or changing a line of code. We are looking for a Security Engineer to protect our global network.',
    requirements: ['5+ years security engineering', 'Experience with network security', 'Penetration testing skills', 'Golang or Rust preferred'],
    responsibilities: ['Build security monitoring systems', 'Respond to security incidents', 'Conduct threat modeling', 'Improve security posture'],
    benefits: ['Fully remote', 'Equity', 'Health benefits', 'Learning budget', 'Flexible PTO'],
    skills: ['Go', 'Rust', 'Network Security', 'TLS', 'DDoS mitigation', 'Python'],
    aboutCompany: 'Cloudflare is a global network designed to make everything you connect to the Internet secure, private, fast, and reliable.',
  },
  {
    id: 105,
    title: 'Data Engineer',
    company: 'Databricks',
    logo: 'https://logo.clearbit.com/databricks.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$170k – $220k',
    equity: '0.03% – 0.1%',
    posted: 'yesterday',
    category: 'Data',
    type: 'full-time',
    experience: 'Senior',
    description: 'Databricks provides a unified, open analytics platform for building, training, and deploying data, analytics, and AI solutions at scale. Join us to build the data pipelines that power our products.',
    requirements: ['5+ years data engineering', 'Apache Spark expertise', 'Python and Scala', 'Experience with data lakehouse architecture'],
    responsibilities: ['Design and build ETL pipelines', 'Optimize Spark jobs', 'Build self-serve data platform', 'Collaborate with data science team'],
    benefits: ['Competitive cash + equity', 'Medical/dental/vision', '401k', 'Learning stipend', 'Parental leave'],
    skills: ['Python', 'Scala', 'Apache Spark', 'Delta Lake', 'SQL', 'Kafka'],
    aboutCompany: 'Databricks is the data and AI company. More than 10,000 organizations worldwide — including Block, Comcast, Conde Nast, and over 50% of the Fortune 500.',
  },
];

// ─── DESIGN JOBS ─────────────────────────────────────────────────────────────
export const designJobs: Job[] = [
  {
    id: 201,
    title: 'Senior Product Designer',
    company: 'Figma',
    logo: 'https://logo.clearbit.com/figma.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$160k – $210k',
    equity: '0.02% – 0.08%',
    posted: 'today',
    category: 'Product Design',
    type: 'full-time',
    experience: 'Senior',
    description: 'Figma is the world\'s leading collaborative design platform. Join us to design the tools that millions of designers use every day. You will work on core product experiences that shape the future of design.',
    requirements: ['5+ years product design', 'Expert Figma skills', 'Strong systems thinking', 'Experience with design tools products', 'User research skills'],
    responsibilities: ['Design core product features', 'Run user research sessions', 'Build and maintain design systems', 'Collaborate with engineering', 'Set design direction for your area'],
    benefits: ['Hybrid flexible', 'Figma license', 'Health benefits', 'Equity', 'Parental leave', '$2k learning budget'],
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems', 'Motion Design', 'Accessibility'],
    aboutCompany: 'Figma is the collaborative interface design tool. We believe great design is for everyone — individuals, startups, and the world\'s largest companies.',
  },
  {
    id: 202,
    title: 'Head of Design',
    company: 'Linear',
    logo: 'https://logo.clearbit.com/linear.app',
    workStyle: 'Remote',
    location: 'Everywhere',
    salary: '$180k – $240k',
    equity: '0.1% – 0.5%',
    posted: 'today',
    category: 'Marketing',
    type: 'remote',
    experience: 'Lead',
    description: 'Linear is looking for a Head of Design to lead our small but mighty design team. You will set the design direction for the entire product and help us build one of the most beautiful B2B products in the world.',
    requirements: ['8+ years design experience', '3+ years leading design teams', 'Strong product and interaction design', 'Experience shipping B2B SaaS'],
    responsibilities: ['Lead design team of 3-5 designers', 'Set product design direction', 'Partner with CEO on product vision', 'Build design culture', 'Ship beautiful product'],
    benefits: ['Fully remote', 'Significant equity', 'Health benefits', 'Home office setup', 'Annual retreat'],
    skills: ['Product Design', 'Design Leadership', 'Figma', 'Brand Design', 'Motion', 'Design Systems'],
    aboutCompany: 'Linear is the project management tool for high-performance teams. We are small, opinionated, and ship fast. Design is core to everything we do.',
  },
  {
    id: 203,
    title: 'UX Designer - Growth',
    company: 'Stripe',
    logo: 'https://logo.clearbit.com/stripe.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$140k – $185k',
    equity: '0.01% – 0.04%',
    posted: 'today',
    category: 'UX Design',
    type: 'full-time',
    experience: 'Mid',
    description: 'Stripe\'s Growth team is responsible for reducing friction in the developer onboarding and activation experience. We need a UX designer to redesign critical user flows that impact millions of developers.',
    requirements: ['3+ years UX design', 'Data-driven design approach', 'Experience with A/B testing', 'Strong user research skills', 'Developer empathy'],
    responsibilities: ['Design onboarding and activation flows', 'Run A/B experiments', 'Conduct user interviews', 'Work with data team on metrics'],
    benefits: ['Hybrid remote', 'Exceptional benefits', 'RSUs', 'Commuter benefits', 'Great food'],
    skills: ['Figma', 'User Research', 'A/B Testing', 'Prototyping', 'Analytics', 'Interaction Design'],
    aboutCompany: 'Stripe builds financial infrastructure for the internet. We process hundreds of billions of dollars in payments annually for millions of businesses.',
  },
  {
    id: 204,
    title: 'Brand Designer',
    company: 'Notion',
    logo: 'https://logo.clearbit.com/notion.so',
    workStyle: 'Hybrid',
    location: 'New York City',
    salary: '$130k – $170k',
    equity: '0.01% – 0.03%',
    posted: 'yesterday',
    category: 'Brand Design',
    type: 'full-time',
    experience: 'Mid',
    description: 'Notion is looking for a Brand Designer to help evolve our visual identity and bring it to life across campaigns, events, and product. You\'ll shape how Notion looks and feels to the world.',
    requirements: ['3+ years brand design', 'Strong illustration skills', 'Motion design experience', 'Print and digital expertise', 'Portfolio demonstrating range'],
    responsibilities: ['Evolve brand visual system', 'Design campaign assets', 'Create motion graphics', 'Partner with marketing team', 'Maintain brand guidelines'],
    benefits: ['NYC office', 'Health insurance', 'Notion credits', 'Generous PTO', 'Team offsites'],
    skills: ['Figma', 'Illustrator', 'After Effects', 'Brand Identity', 'Motion Design', 'Typography'],
    aboutCompany: 'Notion is a connected workspace where better, faster work happens. We are building an operating system for your life and work.',
  },
  {
    id: 205,
    title: 'Design Systems Engineer',
    company: 'Shopify',
    logo: 'https://logo.clearbit.com/shopify.com',
    workStyle: 'Remote only',
    location: 'Everywhere',
    salary: '$145k – $190k',
    equity: '0.01% – 0.04%',
    posted: 'yesterday',
    category: 'Design Engineering',
    type: 'remote',
    experience: 'Senior',
    description: 'Shopify\'s Polaris team builds the design system used by hundreds of engineers and designers to create consistent experiences across the Shopify platform. We need a Design Systems Engineer who bridges design and engineering.',
    requirements: ['4+ years design systems', 'React component library experience', 'Strong CSS/design fundamentals', 'Accessibility expertise', 'Figma token experience'],
    responsibilities: ['Build and maintain Polaris components', 'Write design system documentation', 'Partner with designers on token system', 'Advocate for accessibility'],
    benefits: ['Fully remote', 'RSUs', 'Top health benefits', '$1500 equipment budget', 'Digital nomad friendly'],
    skills: ['React', 'TypeScript', 'CSS', 'Figma', 'Accessibility', 'Storybook'],
    aboutCompany: 'Shopify is the leading global commerce platform. We power over 1.7 million businesses in more than 175 countries.',
  },
];

// ─── MARKETING JOBS ──────────────────────────────────────────────────────────
export const marketingJobs: Job[] = [
  {
    id: 301,
    title: 'VP of Marketing',
    company: 'Airtable',
    logo: 'https://logo.clearbit.com/airtable.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$250k – $320k',
    equity: '0.05% – 0.2%',
    posted: 'today',
    category: 'Marketing',
    type: 'full-time',
    experience: 'Executive',
    description: 'Airtable is looking for a VP of Marketing to lead our go-to-market strategy as we scale to the next level. You will own brand, demand generation, product marketing, and communications.',
    requirements: ['10+ years marketing leadership', 'PLG and enterprise GTM experience', 'B2B SaaS background', 'Data-driven decision making', 'Strong team-building skills'],
    responsibilities: ['Lead marketing org of 20+', 'Own brand and demand gen strategy', 'Drive pipeline and revenue', 'Partner with sales and product', 'Build marketing infrastructure'],
    benefits: ['Competitive salary + equity', 'Full health benefits', '401k match', 'Flexible PTO', 'Parental leave'],
    skills: ['B2B Marketing', 'Demand Generation', 'Brand Strategy', 'PLG', 'Analytics', 'Team Leadership'],
    aboutCompany: 'Airtable is a low-code platform for building collaborative apps. We empower people closest to the work to accelerate their most important business processes.',
  },
  {
    id: 302,
    title: 'Head of Content Marketing',
    company: 'HubSpot',
    logo: 'https://logo.clearbit.com/hubspot.com',
    workStyle: 'Remote',
    location: 'US',
    salary: '$150k – $190k',
    equity: '0.01% – 0.03%',
    posted: 'today',
    category: 'Marketing',
    type: 'remote',
    experience: 'Lead',
    description: 'HubSpot is looking for a Head of Content Marketing to lead our content strategy and team. You will oversee the blog, thought leadership, SEO, and content distribution that drives millions of visitors to HubSpot.com.',
    requirements: ['7+ years content marketing', '3+ years managing content teams', 'SEO expertise', 'Strong editorial background', 'Data-driven approach to content'],
    responsibilities: ['Lead content marketing team of 8', 'Own blog and SEO strategy', 'Develop thought leadership content', 'Build content distribution programs', 'Drive organic growth'],
    benefits: ['Remote first', 'RSUs', 'Health benefits', 'Unlimited PTO', 'Learning & development budget'],
    skills: ['Content Strategy', 'SEO', 'Editorial', 'HubSpot', 'Analytics', 'Team Management'],
    aboutCompany: 'HubSpot is a leading CRM platform that provides software and support to help businesses grow better.',
  },
  {
    id: 303,
    title: 'Growth Marketing Manager',
    company: 'Calendly',
    logo: 'https://logo.clearbit.com/calendly.com',
    workStyle: 'Remote',
    location: 'US',
    salary: '$110k – $145k',
    equity: '0.01% – 0.02%',
    posted: 'today',
    category: 'Marketing',
    type: 'remote',
    experience: 'Mid',
    description: 'Calendly is the scheduling platform for leading organizations. We are looking for a Growth Marketing Manager to own our paid and organic growth channels and help us scale to 30M+ users.',
    requirements: ['4+ years growth marketing', 'Paid acquisition expertise', 'Strong SQL skills', 'A/B testing experience', 'PLG knowledge'],
    responsibilities: ['Manage paid acquisition budget', 'Run growth experiments', 'Optimize conversion funnels', 'Build growth models', 'Report on growth metrics'],
    benefits: ['Remote flexible', 'Health benefits', 'Equity', '401k', 'Home office stipend'],
    skills: ['Paid Acquisition', 'SQL', 'Google Ads', 'Facebook Ads', 'A/B Testing', 'Analytics'],
    aboutCompany: 'Calendly is the world\'s #1 scheduling tool. We eliminate the "when are you free?" back-and-forth so you can focus on the work that matters.',
  },
  {
    id: 304,
    title: 'Product Marketing Manager',
    company: 'Intercom',
    logo: 'https://logo.clearbit.com/intercom.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$130k – $165k',
    equity: '0.01% – 0.03%',
    posted: 'yesterday',
    category: 'Marketing',
    type: 'full-time',
    experience: 'Mid',
    description: 'Intercom is the AI-first customer service platform. We need a Product Marketing Manager to own positioning, messaging, and GTM for our AI-powered products. You\'ll work at the intersection of product, sales, and marketing.',
    requirements: ['4+ years product marketing', 'B2B SaaS experience', 'Strong writing skills', 'Sales enablement experience', 'Customer research skills'],
    responsibilities: ['Own product positioning and messaging', 'Drive product launch strategy', 'Build sales enablement materials', 'Conduct customer research', 'Present at company all-hands'],
    benefits: ['Hybrid schedule', 'Equity', 'Health benefits', 'Catered lunches', 'Learning budget'],
    skills: ['Product Marketing', 'Positioning', 'GTM Strategy', 'Sales Enablement', 'Customer Research', 'Writing'],
    aboutCompany: 'Intercom is the AI-first customer service platform, helping businesses scale support while maintaining quality and speed.',
  },
  {
    id: 305,
    title: 'Social Media Manager',
    company: 'Figma',
    logo: 'https://logo.clearbit.com/figma.com',
    workStyle: 'Hybrid',
    location: 'San Francisco',
    salary: '$90k – $115k',
    equity: '0.005% – 0.01%',
    posted: 'yesterday',
    category: 'Marketing',
    type: 'full-time',
    experience: 'Mid',
    description: 'Figma\'s community is one of the most vibrant in design. We\'re looking for a Social Media Manager who loves design, understands the Figma community, and can grow our presence across all platforms.',
    requirements: ['3+ years social media management', 'Design community knowledge', 'Content creation skills', 'Analytics proficiency', 'Experience with design tools'],
    responsibilities: ['Manage all Figma social channels', 'Create and curate content', 'Engage with design community', 'Track and report on metrics', 'Run social campaigns'],
    benefits: ['SF office hybrid', 'Health benefits', 'Figma swag', 'Learning budget', 'Team events'],
    skills: ['Social Media', 'Content Creation', 'Community Management', 'Analytics', 'Figma', 'Copywriting'],
    aboutCompany: 'Figma is a collaborative design platform used by millions of designers, developers, and product teams worldwide.',
  },
];

// ─── Combined lookup ──────────────────────────────────────────────────────────
export const allCategoryJobs = [...remoteJobs, ...techJobs, ...designJobs, ...marketingJobs];

export function getJobById(id: number): Job | undefined {
  return allCategoryJobs.find((j) => j.id === id);
}
