const keywordSuggestions = [
    "Software Development",
    "Web Development",
    "Frontend",
    "Backend",
    "Full Stack",
    "React",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express.js",
    "JavaScript",
    "TypeScript",
    "Java",
    "Spring Boot",
    "Python",
    "Django",
    "Flask",
    "C#",
    ".NET",
    "PHP",
    "Laravel",
    "Ruby",
    "Ruby on Rails",
    "C++",
    "C",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Objective-C",
    "Mobile Development",
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Remote",
    "Digital Marketing",
    "Graphic Design",
    "UI/UX",
    "Machine Learning",
    "Deep Learning",
    "Data Science",
    "Data Analysis",
    "DevOps",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Copywriting",
    "SEO",
    "Content Writing",
    "Project Management",
    "Agile",
    "Scrum",
    "Testing",
    "QA",
    "Automation",
    "SDET",
    "Cybersecurity",
    "Blockchain",
    "Solidity",
    "Smart Contracts",
    "Game Development",
    "Unity",
    "Unreal Engine",
    "Database",
    "SQL",
    "NoSQL",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "Cloud Computing",
    "System Administration",
    "Technical Support",
    "Business Analysis",
    "Product Management",
    "Salesforce",
    "SAP",
    "Networking",
    "Linux",
    "Shell Scripting",
    "PowerShell",
    "E-commerce",
    "Shopify",
    "WordPress",
    "Magento",
    "Big Data",
    "Hadoop",
    "Spark",
    "Artificial Intelligence",
    "NLP",
    "Computer Vision"
];

export default keywordSuggestions;